"""ledger_numeric_precision_and_success_constraint

Revision ID: 61467b402d65
Revises: eefa9f8b2e79
Create Date: 2026-05-28 16:16:40.763543

"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '61467b402d65'
down_revision: Union[str, None] = 'eefa9f8b2e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ledger_entries', 'our_cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=10),
               existing_comment='Cost computed from pricing/models.yaml at request time.',
               existing_nullable=False)
    op.alter_column('ledger_entries', 'provider_reported_cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=10),
               existing_comment='Cost figure reported by the provider where available, e.g. Bedrock.',
               existing_nullable=True)
    op.alter_column('policies', 'budget_usd_monthly',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_comment='Monthly cost ceiling in USD. Null means no budget limit.',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('policies', 'budget_usd_monthly',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_comment='Monthly cost ceiling in USD. Null means no budget limit.',
               existing_nullable=True)
    op.alter_column('ledger_entries', 'provider_reported_cost_usd',
               existing_type=sa.Numeric(precision=18, scale=10),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_comment='Cost figure reported by the provider where available, e.g. Bedrock.',
               existing_nullable=True)
    op.alter_column('ledger_entries', 'our_cost_usd',
               existing_type=sa.Numeric(precision=18, scale=10),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_comment='Cost computed from pricing/models.yaml at request time.',
               existing_nullable=False)
    # ### end Alembic commands ###