"""add_tenant_defaults

Revision ID: a3f7c9d1e284
Revises: 61467b402d65
Create Date: 2026-08-31 00:00:00.000000

"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


revision: str = 'a3f7c9d1e284'
down_revision: Union[str, None] = '61467b402d65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_defaults',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key.'),
    sa.Column('tenant_id', sa.String(), nullable=False, comment='FK to tenants.id. One defaults row per tenant.'),
    sa.Column('default_provider', sa.String(), nullable=True, comment='Provider to use when the request omits provider and opts into defaults.'),
    sa.Column('default_model', sa.String(), nullable=True, comment='Model to use when the request omits model and opts into defaults.'),
    sa.Column('default_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='ChatParams-shaped dict merged into the request for any field the request omits.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp (UTC).'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Last modification timestamp (UTC). Null until the first update.'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant_defaults')
    # ### end Alembic commands ###
