"""initial_schema

Revision ID: b034ce8f8acd
Revises: 
Create Date: 2026-05-12 13:06:23.686175

"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'b034ce8f8acd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calling_services',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key.'),
    sa.Column('name', sa.String(), nullable=False, comment='Service name, e.g. taxbot-inc.'),
    sa.Column('bearer_token_hash', sa.String(), nullable=False, comment='SHA-256 of the bearer token. Raw token is never persisted.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp (UTC).'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bearer_token_hash')
    )
    op.create_table('tenants',
    sa.Column('id', sa.String(), nullable=False, comment='Slug-style identifier, e.g. tenant_acme. Used as FK in every other table.'),
    sa.Column('name', sa.String(), nullable=False, comment='Human-readable display name.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp (UTC).'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calling_service_tenants',
    sa.Column('calling_service_id', sa.UUID(), nullable=False, comment='The calling service being granted access. Cascade-deletes this row when the service is removed.'),
    sa.Column('tenant_id', sa.String(), nullable=False, comment='The tenant this service is permitted to act on behalf of. Cascade-deletes this row when the tenant is removed.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this access grant was created (UTC).'),
    sa.ForeignKeyConstraint(['calling_service_id'], ['calling_services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('calling_service_id', 'tenant_id')
    )
    op.create_table('ledger_entries',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key.'),
    sa.Column('request_id', sa.String(), nullable=False, comment='Client-supplied or gateway-generated idempotency key.'),
    sa.Column('tenant_id', sa.String(), nullable=False, comment='FK to tenants.id.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp (UTC).'),
    sa.Column('provider', sa.String(), nullable=False, comment='LLM provider that handled the call, e.g. openai, anthropic, bedrock.'),
    sa.Column('model', sa.String(), nullable=False, comment='Canonical model ID as sent in the request.'),
    sa.Column('transport', sa.Enum('litellm', 'direct', name='transport', native_enum=False), nullable=False, comment='Whether the call was routed through the LiteLLM SDK or a direct adapter.'),
    sa.Column('region', sa.String(), nullable=True, comment='Cloud region the upstream call was routed to, e.g. us-east-1.'),
    sa.Column('feature', sa.Enum('chat', 'stream', 'embed', 'tool', name='feature', native_enum=False), nullable=False, comment='Request type executed: chat | stream | embed | tool.'),
    sa.Column('tokens_in', sa.Integer(), nullable=False, comment='Prompt tokens reported by the provider.'),
    sa.Column('tokens_out', sa.Integer(), nullable=False, comment='Completion tokens reported by the provider.'),
    sa.Column('input_tokens_cache_write', sa.Integer(), nullable=True, comment='Tokens written to provider-side prompt cache, billed at cache write rate.'),
    sa.Column('input_tokens_cache_read', sa.Integer(), nullable=True, comment='Tokens served from provider-side prompt cache, billed at cache read rate.'),
    sa.Column('upstream_prompt_cache_hit', sa.Boolean(), nullable=True, comment='True if any input tokens were served from the provider-side prompt cache.'),
    sa.Column('our_cost_usd', sa.Float(), nullable=False, comment='Cost computed from pricing/models.yaml at request time.'),
    sa.Column('pricing_version', sa.Integer(), nullable=False, comment='pricing_version from models.yaml used to compute our_cost_usd. Allows historical cost re-computation.'),
    sa.Column('provider_reported_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Raw usage block from the provider response, stored verbatim for billing audit.'),
    sa.Column('provider_reported_cost_usd', sa.Float(), nullable=True, comment='Cost figure reported by the provider where available, e.g. Bedrock.'),
    sa.Column('latency_ms', sa.Integer(), nullable=False, comment='Total wall-clock time in ms from request receipt to response sent.'),
    sa.Column('time_to_first_token_ms', sa.Integer(), nullable=True, comment='Time in ms to the first streaming token. Null for non-streaming requests.'),
    sa.Column('status', sa.Enum('success', 'error', 'partial_response', name='ledgerstatus', native_enum=False), nullable=False, comment='Outcome of the request: success | error | partial_response.'),
    sa.Column('error_code', sa.String(), nullable=True, comment='Structured error code when status is error or partial_response.'),
    sa.Column('our_cache_hit', sa.Boolean(), nullable=False, comment='True if the response was served from our exact-match Redis cache.'),
    sa.Column('batched', sa.Boolean(), nullable=False, comment='True if the request was submitted via the OpenAI/Anthropic batch API.'),
    sa.Column('guardrail_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Presidio/Llama-Guard events: which rules fired and what was redacted.'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key.'),
    sa.Column('tenant_id', sa.String(), nullable=False, comment='FK to tenants.id. One policy row per tenant.'),
    sa.Column('max_tokens_per_request', sa.Integer(), nullable=True, comment='Hard cap on max_tokens per request. Requests over this are rejected with 429.'),
    sa.Column('rate_limit_rpm', sa.Integer(), nullable=True, comment='Maximum requests per minute. Null means no rate limit.'),
    sa.Column('budget_usd_monthly', sa.Float(), nullable=True, comment='Monthly cost ceiling in USD. Null means no budget limit.'),
    sa.Column('allowed_models', postgresql.ARRAY(sa.String()), nullable=True, comment='Whitelist of model IDs this tenant may use. Null means all models are allowed.'),
    sa.Column('denied_models', postgresql.ARRAY(sa.String()), nullable=True, comment='Blacklist of model IDs this tenant may not use. Null means none are denied.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp (UTC).'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Last modification timestamp (UTC). Null until the first update.'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_table('tenant_keys',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key.'),
    sa.Column('tenant_id', sa.String(), nullable=False, comment='FK to tenants.id.'),
    sa.Column('provider', sa.String(), nullable=False, comment='Provider identifier, e.g. openai, anthropic, bedrock. Not an enum — new providers must not require a migration.'),
    sa.Column('key_format', sa.Enum('api_key', 'aws_credentials', 'endpoint_pair', name='keyformat', native_enum=False), nullable=False, comment='Shape of the decrypted JSON payload: api_key | aws_credentials | endpoint_pair.'),
    sa.Column('encrypted_payload', sa.Text(), nullable=False, comment='Fernet-encrypted JSON. Shape is determined by key_format.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp (UTC).'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'provider', name='uq_tenant_provider')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant_keys')
    op.drop_table('policies')
    op.drop_table('ledger_entries')
    op.drop_table('calling_service_tenants')
    op.drop_table('tenants')
    op.drop_table('calling_services')
    # ### end Alembic commands ###