"""add batch_jobs submit_attempts

Revision ID: eefa9f8b2e79
Revises: b034ce8f8acd
Create Date: 2026-05-19 14:48:41.109046

"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'eefa9f8b2e79'
down_revision: Union[str, None] = 'b034ce8f8acd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_jobs',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key. Used as custom_id in the upstream batch API request.'),
    sa.Column('request_id', sa.String(), nullable=False, comment='Gateway-level request ID — same idempotency key as ledger_entries.request_id.'),
    sa.Column('tenant_id', sa.String(), nullable=False, comment='FK to tenants.id. Used to reload the BYOK key at submission time.'),
    sa.Column('provider', sa.String(), nullable=False, comment='Provider that will handle the batch, e.g. openai, anthropic.'),
    sa.Column('model', sa.String(), nullable=False, comment='Canonical model ID as sent in the original request.'),
    sa.Column('normalised_request', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='NormalisedLLMRequest serialised as JSONB. Reconstructed at submission time.'),
    sa.Column('upstream_batch_id', sa.String(), nullable=True, comment='Provider batch job ID, e.g. OpenAI batch_xxx or Anthropic msgbatch_xxx.'),
    sa.Column('upstream_file_id', sa.String(), nullable=True, comment='OpenAI input file ID (file_xxx). Null for Anthropic.'),
    sa.Column('status', sa.Enum('pending', 'submitted', 'complete', 'failed', name='batchjobstatus', native_enum=False), nullable=False, comment='Lifecycle state: pending → submitted → complete | failed.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp (UTC).'),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True, comment='When the job was submitted to the provider batch API (UTC).'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='When the result was retrieved from the provider (UTC).'),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='ChatResponse serialised as JSONB. Populated when status=complete.'),
    sa.Column('submit_attempts', sa.Integer(), nullable=False, comment='Number of times batch_submit has tried (and failed) to send this job to the provider.'),
    sa.Column('error_code', sa.String(), nullable=True, comment='Structured error code when status=failed.'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('batch_jobs')
    # ### end Alembic commands ###